# Generated by Django 4.2.5 on 2023-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birthday', models.DateField(verbose_name='Birthday Date')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('work_anniversary', 'Work Anniversary ')], max_length=255, unique=True, verbose_name='Event Type')),
                ('template', models.TextField(verbose_name='Email Template')),
            ],
        ),
        migrations.CreateModel(
            name='LastExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_execution_time', models.DateTimeField(auto_now=True, verbose_name='Last Execution Time')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Created At')),
                ('log_type', models.CharField(choices=[('while_sending_email', 'While Sending Email'), ('no_event', 'No Event')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('event_type', models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('work_anniversary', 'Work Anniversary ')], max_length=255, null=True, verbose_name='Event Type')),
                ('is_success', models.BooleanField(verbose_name='Is Success')),
                ('message', models.TextField(verbose_name='Message')),
                ('error_message', models.TextField(verbose_name='Error Message')),
            ],
        ),
    ]
